spring.application.name=myproject
server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/your_database_name
spring.datasource.username=postgres
spring.datasource.password=ypur password
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect